# Usamos Ubuntu 24.04 como base
FROM ubuntu:24.04

# Evitamos prompts interactivos
ENV DEBIAN_FRONTEND=noninteractive

# Instalamos sudo, editores y cron
RUN apt-get update && \
    apt-get install -y sudo nano vim cron && \
    rm -rf /var/lib/apt/lists/*

# Dejamos al usuario en la raíz temporalmente
WORKDIR /

# Simplemente mantenemos el contenedor vivo
CMD ["/bin/bash"]
