# Usamos Ubuntu 24.04 como base
FROM ubuntu:24.04

# Evitamos prompts interactivos
ENV DEBIAN_FRONTEND=noninteractive

# Instalamos FRRouting (la magia para emular Cisco IOS) y utilidades de red
RUN apt-get update && \
    apt-get install -y sudo nano frr iproute2 net-tools iputils-ping && \
    rm -rf /var/lib/apt/lists/*

# Dejamos al usuario en el directorio principal
WORKDIR /root

# Mantenemos el contenedor vivo
CMD ["/bin/bash"]
